spec:
  replicas: 3
  template:
    spec:
      serviceAccount: leader
      containers:
      - env:
        - name: NARAYANA_NODE_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.name